//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY_Mini_Ağrı_Projesi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MY_Mini_Ağrı_Projesi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abdigörköftesi {
            get {
                object obj = ResourceManager.GetObject("abdigörköftesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agridagi {
            get {
                object obj = ResourceManager.GetObject("agridagi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agriharitasi {
            get {
                object obj = ResourceManager.GetObject("agriharitasi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap agrimerkez_genel {
            get {
                object obj = ResourceManager.GetObject("agrimerkez_genel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ağrıyaprakdöneri {
            get {
                object obj = ResourceManager.GetObject("ağrıyaprakdöneri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ayranaşı {
            get {
                object obj = ResourceManager.GetObject("ayranaşı", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap balıkgolu {
            get {
                object obj = ResourceManager.GetObject("balıkgolu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap çirişketesi {
            get {
                object obj = ResourceManager.GetObject("çirişketesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diyadin_genel {
            get {
                object obj = ResourceManager.GetObject("diyadin_genel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diyadinkaplicalari {
            get {
                object obj = ResourceManager.GetObject("diyadinkaplicalari", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diyadin, Ağrı ilinin köklü tarihî yerleşimlerinden biridir. İlçenin tarihi Urartular dönemine kadar uzanmakta olup, bölge tarih boyunca stratejik konumu nedeniyle birçok medeniyetin hâkimiyetine girmiştir. Urartuların ardından Persler, Romalılar, Bizanslılar ve Selçuklular bölgede etkili olmuştur.
        ///
        ///1071 Malazgirt Zaferi’nden sonra Diyadin ve çevresi Türk hâkimiyetine girmiş, daha sonraki dönemlerde İlhanlılar ve Karakoyunluların yönetiminde kalmıştır. 16. yüzyılda Osmanlı Devleti’ne bağlanan ilçe, uzun sü [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diyadintarihi {
            get {
                return ResourceManager.GetString("diyadintarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dogubeyazit_genel {
            get {
                object obj = ResourceManager.GetObject("dogubeyazit_genel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğubayazıt, Ağrı ilinin en köklü tarihine sahip ilçelerinden biridir. İlçenin tarihi, Urartular dönemine kadar uzanmakta olup Eski Beyazıt ve çevresinde Urartu mezarları bulunmaktadır. İlk yerleşim Yukarı Beyazıt’taki eski kale çevresinde kurulmuştur ve bölge uzun süre önemli bir gümrük ve geçiş merkezi olarak gelişmiştir.
        ///
        ///Tarih boyunca Urartular, Persler, Romalılar, Bizanslılar, Selçuklular, Moğollar, Karakoyunlular, Akkoyunlular ve Osmanlılar bölgeye hâkim olmuştur. 1514 Çaldıran Savaşı’ndan sonra Osm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dogubeyazittarihi {
            get {
                return ResourceManager.GetString("dogubeyazittarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleşkirt, Ağrı ilinin tarihî ilçelerinden biridir ve geçmişi Urartular dönemine kadar uzanmaktadır. İlçe, tarih boyunca Doğu Anadolu’yu İran ve Kafkasya’ya bağlayan yollar üzerinde yer aldığı için stratejik bir öneme sahip olmuştur.
        ///
        ///Bölge sırasıyla Urartular, Persler, Romalılar, Bizanslılar ve Selçukluların hâkimiyetine girmiştir. 1071 Malazgirt Zaferi’nden sonra Eleşkirt ve çevresi Türk hâkimiyetine katılmış, ilerleyen dönemlerde İlhanlılar ve Karakoyunlular tarafından yönetilmiştir.
        ///
        ///yüzyılda Osmanlı [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eleskirttarihi {
            get {
                return ResourceManager.GetString("eleskirttarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elşkrt_genel {
            get {
                object obj = ResourceManager.GetObject("elşkrt_genel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap geceagridagi {
            get {
                object obj = ResourceManager.GetObject("geceagridagi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gevenbalı {
            get {
                object obj = ResourceManager.GetObject("gevenbalı", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gösteberg {
            get {
                object obj = ResourceManager.GetObject("gösteberg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamur, Ağrı ilinin güneybatısında yer alan ve tarihi Urartular dönemine kadar uzanan eski yerleşim alanlarından biridir. Bölge, tarih boyunca Doğu Anadolu’yu İran ve iç Anadolu’ya bağlayan yollar üzerinde bulunması nedeniyle stratejik bir öneme sahip olmuştur.
        ///
        ///Urartuların ardından Persler, Romalılar, Bizanslılar ve Selçuklular bölgede hâkimiyet kurmuştur. 1071 Malazgirt Zaferi’nden sonra Hamur ve çevresi Türk hâkimiyetine girmiş, ilerleyen dönemlerde İlhanlılar ve Karakoyunluların yönetiminde kalmıştır.        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hamurtarihi {
            get {
                return ResourceManager.GetString("hamurtarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap haşılyemeği {
            get {
                object obj = ResourceManager.GetObject("haşılyemeği", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hasude {
            get {
                object obj = ResourceManager.GetObject("hasude", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hengel {
            get {
                object obj = ResourceManager.GetObject("hengel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hmr_genel {
            get {
                object obj = ResourceManager.GetObject("hmr_genel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ishakpasasarayi {
            get {
                object obj = ResourceManager.GetObject("ishakpasasarayi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Klasik_Muzik_Schubert_Ave_Maria_Opera {
            get {
                return ResourceManager.GetStream("Klasik_Muzik_Schubert_Ave_Maria_Opera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağrı, Doğu Anadolu Bölgesi’nin en eski yerleşim alanlarından biridir ve tarihi Urartular dönemine kadar uzanmaktadır. Bölge, stratejik konumu nedeniyle tarih boyunca birçok medeniyetin egemenliği altına girmiştir. Urartuların ardından Persler, Romalılar, Bizanslılar ve Selçuklular Ağrı ve çevresinde hâkimiyet kurmuştur.
        ///
        ///1071 Malazgirt Zaferi’nden sonra Ağrı ve çevresi Türk hâkimiyetine girmiştir. Daha sonraki dönemlerde İlhanlılar, Karakoyunlular ve Akkoyunlular bölgeye egemen olmuştur. 16. yüzyılda Osma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string merkeztarihi {
            get {
                return ResourceManager.GetString("merkeztarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap meteorcukuru {
            get {
                object obj = ResourceManager.GetObject("meteorcukuru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nuhungemisi {
            get {
                object obj = ResourceManager.GetObject("nuhungemisi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patnos, Ağrı ilinin en eski yerleşim alanlarından biridir ve tarihi Urartular dönemine kadar uzanmaktadır. İlçe, stratejik konumu nedeniyle tarih boyunca birçok medeniyetin hâkimiyetine girmiştir. Bölge sırasıyla Urartular, Persler, Romalılar, Bizanslılar ve Selçuklular tarafından yönetilmiştir.
        ///
        ///1071 Malazgirt Zaferi’nden sonra Patnos ve çevresi Türklerin hâkimiyetine girmiş, Selçuklu Devleti’ne bağlanmıştır. Daha sonraki dönemlerde Moğollar, İlhanlılar ve Karakoyunlular bölgede etkili olmuştur. 16. yüzy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string patnostarihi {
            get {
                return ResourceManager.GetString("patnostarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ptns_genel {
            get {
                object obj = ResourceManager.GetObject("ptns_genel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sabahagridagi {
            get {
                object obj = ResourceManager.GetObject("sabahagridagi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selekeli {
            get {
                object obj = ResourceManager.GetObject("selekeli", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taşlıçay, Ağrı ilinin doğusunda yer alan ve tarihi Urartular dönemine kadar uzanan eski yerleşim alanlarından biridir. Bölge, tarih boyunca Doğu Anadolu’yu İran ve Kafkasya’ya bağlayan yollar üzerinde bulunması nedeniyle stratejik bir konuma sahip olmuştur.
        ///
        ///Urartuların ardından Persler, Romalılar, Bizanslılar ve Selçuklular bölgede hâkimiyet kurmuştur. 1071 Malazgirt Zaferi’nden sonra Taşlıçay ve çevresi Türk hâkimiyetine girmiş, ilerleyen dönemlerde İlhanlılar ve Karakoyunluların yönetiminde kalmıştır.        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string taslicaytarihi {
            get {
                return ResourceManager.GetString("taslicaytarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tendüreklavakintilari {
            get {
                object obj = ResourceManager.GetObject("tendüreklavakintilari", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tşlçy_genel {
            get {
                object obj = ResourceManager.GetObject("tşlçy_genel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ttk_genel {
            get {
                object obj = ResourceManager.GetObject("ttk_genel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutak, Ağrı ilinin batısında yer alan ve tarihi Urartular dönemine kadar uzanan eski bir yerleşim alanıdır. Bölge, tarih boyunca Doğu Anadolu’yu iç kesimlere bağlayan yollar üzerinde bulunması nedeniyle stratejik bir öneme sahip olmuştur.
        ///
        ///Urartuların ardından Persler, Romalılar, Bizanslılar ve Selçuklular bölgede hâkimiyet kurmuştur. 1071 Malazgirt Zaferi’nden sonra Tutak ve çevresi Türk hâkimiyetine girmiş, daha sonraki dönemlerde İlhanlılar ve Karakoyunluların yönetiminde kalmıştır.
        ///
        ///yüzyılda Osmanlı [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tutaktarihi {
            get {
                return ResourceManager.GetString("tutaktarihi", resourceCulture);
            }
        }
    }
}
